### ISSUE TITLE
[PE-D][Tester E] scroll pane freezes if window is resized smaller

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#325] opened 2024-11-08 23:04 UTC
`clear`
`add n/name tele/@telegram e/email@email github/github`
`add n/name2 tele/@telegram e/email@email github/github`
`add n/name3 tele/@telegram e/email@email github/github`
`add n/name4 tele/@telegram e/email@email github/github`
`add n/name5 tele/@telegram e/email@email github/github`

then resize the right hand side, scroll pane is now frozen

<i><video controls><source src="https://raw.githubusercontent.com/somethingfishyfishy/ped/main/files/6d4f7521-5d4f-4b92-a530-42e05afedc95.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/somethingfishyfishy/ped/main/files/6d4f7521-5d4f-4b92-a530-42e05afedc95.mp4</i>

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: somethingfishyfishy/ped#5

**Comment by DesSnowy** [comment] 2024-11-09 04:57
duplicate of #326

**Closed** 2024-11-09 04:57 UTC
