### ISSUE TITLE
[PE-D][Tester E] User Guide pg 11: misleading example for email

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#301] opened 2024-11-08 18:30 UTC
The box is highlighting email restrictions but you have put examples for tags. Perhaps you are intending the examples for emails?

![image.png](https://raw.githubusercontent.com/somethingfishyfishy/ped/main/files/4f2e109c-1df7-4dda-9a17-e07c7b79fa0f.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: somethingfishyfishy/ped#2

**Comment by Incogdino** [comment] 2024-11-09 03:32
This needs updating

**Comment by DesSnowy** [comment] 2024-11-09 03:35
Duplicate of #293

**Closed by DesSnowy** 2024-11-09 03:35 UTC
Labels: priority.High
